---
title: "Bird dispersal quality"
author: "Elena Quintero"
date: "`r Sys.Date()`"
output: github_document
---

```{r, message=F}
library(here)
library(stringr)
library(tidyr)
library(tidylog)
library(dplyr)
```

**General** Prob. bird MH use (microhabitats are equally likely probable):

```{r}
P.disp.seed.mh <- readRDS(here("../Pistacia_effectiveness/analysis/output/Pdisperse.bird.mh.rds"))

P.disp.seed.mh <- P.disp.seed.mh %>%
  mutate(mh_use = paste0("Prob.bird.mh_", mh)) %>%
  dplyr::select(bird_sp, mh_use, Prob.bird.mh) %>%
  pivot_wider(names_from = mh_use, values_from = Prob.bird.mh, values_fn = list) %>%
  unnest(cols = c(Prob.bird.mh_FR, 
                  Prob.bird.mh_NF, 
                  Prob.bird.mh_OA, 
                  Prob.bird.mh_PL,
                  Prob.bird.mh_PP))

glimpse(P.disp.seed.mh)
```

**El Puntal** Prob. bird MH use:

```{r}
P.disp.seed.mh.cover <- readRDS(here("data/Pdisperse.bird.mh.cover.rds"))

P.disp.seed.mh.cover <- P.disp.seed.mh.cover %>%
  mutate(mh_use = paste0("Prob.bird.mh.cover_", mh)) %>%
  dplyr::select(bird_sp, mh_use, Prob.bird.mh) %>%
  pivot_wider(names_from = mh_use, values_from = Prob.bird.mh, values_fn = list) %>%
  unnest(cols = c(Prob.bird.mh.cover_FR, 
                  Prob.bird.mh.cover_NF, 
                  Prob.bird.mh.cover_OA, 
                  Prob.bird.mh.cover_PL,
                  Prob.bird.mh.cover_PP))

glimpse(P.disp.seed.mh.cover)
```

Prob escape rodent pred:

```{r}
pred <- readRDS(here("../Pistacia_effectiveness/analysis/output/pred.mh.post.long.rds"))

pred.wide <- pred %>%
  mutate(mh_pred = paste0("Prob.escaping.pred_", mh)) %>%
  dplyr::select(mh_pred, Prob.escaping.pred) %>%
  pivot_wider(names_from = mh_pred, values_from = Prob.escaping.pred, values_fn = list) %>%
  unnest(cols = c(Prob.escaping.pred_FR, 
                  Prob.escaping.pred_NF, 
                  Prob.escaping.pred_OA, 
                  Prob.escaping.pred_PL,
                  Prob.escaping.pred_PP))

glimpse(pred.wide)
```

Prob emergence:

```{r}
emergence <- readRDS(here("data/emergence.mh.post.rds"))

emer.wide <- emergence %>%
  mutate(mh_emer = paste0("Prob.emergence_", mh)) %>%
  dplyr::select(mh_emer, surv.avg) %>%
  pivot_wider(names_from = mh_emer, values_from = surv.avg, values_fn = list) %>%
  unnest(cols = c(Prob.emergence_FR, 
                  Prob.emergence_NF, 
                  Prob.emergence_OA, 
                  Prob.emergence_PL,
                  Prob.emergence_PP))
  
glimpse(emer.wide)
```

Prob survival 1st summer:

```{r}
surv.1st <- readRDS(here("data/surv.1st.summer.post.rds"))

surv.1st.wide <- surv.1st %>%
  mutate(mh_surv1 = paste0("Prob.surv.1summer_", mh)) %>%
  dplyr::select(mh_surv1, surv.avg) %>%
  pivot_wider(names_from = mh_surv1, values_from = surv.avg, values_fn = list) %>%
  unnest(cols = c(Prob.surv.1summer_FR, 
                  Prob.surv.1summer_NF, 
                  Prob.surv.1summer_OA, 
                  Prob.surv.1summer_PL,
                  Prob.surv.1summer_PP))
  
glimpse(surv.1st.wide)
```

Prob survival 2nd summer:

```{r}
surv.2nd <- readRDS(here("data/surv.2nd.summer.post.rds"))

surv.2nd.wide <- surv.2nd %>%
  mutate(mh_surv2 = paste0("Prob.surv.2summer_", mh)) %>%
  dplyr::select(mh_surv2, surv.avg) %>%
  pivot_wider(names_from = mh_surv2, values_from = surv.avg, values_fn = list) %>%
  unnest(cols = c(Prob.surv.2summer_FR, 
                  Prob.surv.2summer_NF, 
                  Prob.surv.2summer_OA, 
                  Prob.surv.2summer_PL,
                  Prob.surv.2summer_PP))
  
glimpse(surv.2nd.wide)
```

Combine probabilities:

```{r}
mh_qlc <- cbind(pred.wide, emer.wide, surv.1st.wide, surv.2nd.wide)

saveRDS(mh_qlc, here("data/mh.quality.rds"))
```
