---
title: "Probability of seedling surviving 1st summer at each microhabitat"
date: "`r Sys.Date()`"
output: github_document
---


```{r setup, include=FALSE}
set.seed(888)
library(knitr)
knitr::opts_chunk$set(echo = TRUE, out.width = '100%', 
                      cache = TRUE, message = FALSE)
```

```{r }
library(here)
library(readr)
library(dplyr)
library(ggplot2)
suppressPackageStartupMessages(library(tidylog))
library(DHARMa.helpers)
# source(here("R/check_brms.R"))

theme_set(theme_minimal())
```


Load data:

```{r}
mhdata <- read_csv(here("data/seedling_emergence.csv"), guess_max = 10000)

## Select only seeds emerged
mhdata_emer <- mhdata %>%
  filter(emerged_status == 1)

## Using mid-October census
mhdata_emerged <- mhdata_emer %>%
  filter(revision_date %in% as.Date(c("2019-10-23", "2020-10-14"))) %>% 
  filter(! (season == "2018-19" & revision_date > as.Date("2019-10-31"))) %>%  # consider only first summer census (ie. remove 2nd summer) 
  filter(! (season == "2019-20" & revision_date == as.Date("2019-10-23"))) %>% 
  mutate(year = ifelse(season == "2018-19", "2019", "2020")) %>% 
  mutate(alive = as.numeric(alive))  # censored now coded as NA

table(mhdata_emerged$season, mhdata_emerged$sowing_date)
table(mhdata_emerged$season, mhdata_emerged$revision_date)
table(mhdata_emerged$season, mhdata_emerged$germin_station)
table(mhdata_emerged$season, mhdata_emerged$alive)

mhdata_emerged %>% 
  filter(is.na(alive)) %>%
  group_by(season, mh) %>% 
  summarise(n())

mhdata_emerged <- mhdata_emerged %>% 
  filter(!is.na(alive)) %>%
  group_by(season, germin_station) %>%
  mutate(emerged_seeds = n())

# Summary
table(mhdata_emerged$mh, mhdata_emerged$alive, mhdata_emerged$season)
```




## Model seedling survival to 1st summer

We model, for every seed that emerged, the probability of surviving the first summer, across microhabitats and years (2018-19 & 2019-20).

There are 5 microhabitats (MH), with varible number of emerged seeds per MH.


### Prior Predictive Check


```{r }
library("brms")

surv.formu <- brmsformula(alive ~ mh * year + (1 | germin_station),
                            # offset(log(emerged_seeds)), 
                            family = bernoulli())

get_prior(surv.formu, data = mhdata_emerged)

## priors (logit scale)
# plogis(-0.5) = 0.40  (40% survival)
# plogis(-1.4) = 0.20 (20% survival)
plot(density(plogis(rnorm(10000, -1.4, 2))), xlim = c(0,1))

priors <- c(
  prior(normal(-1.4, 2), class = "Intercept"), 
  prior(normal(0, 2), class = "b"),
  prior(normal(0, 1), class = "sd")
)

# priors <- c(
#   prior(normal(-6.9, 2), class = "Intercept"),
#   prior(normal(0, 1), class = "b"),
#   prior(lkj(2), class = "cor"),
#   prior(normal(0, 1), class = "sd", group = "mh", coef = "year2020")
# )
```


Prior predictive check:

```{r eval=TRUE}
surv.m <- brm(surv.formu,
         data = mhdata_emerged,
         prior = priors,
         sample_prior = "only",
         cores = 4,
         iter = 2000,
         refresh = 0)

# stancode(surv.m)
pp_check(surv.m, ndraws = 100, type = "bars") 
summary(surv.m, priors = TRUE)
plot(surv.m, ask = FALSE)
```



### Fit model


```{r }
surv.m <- brm(surv.formu,
         data = mhdata_emerged, 
         prior = priors,
         cores = 4,
         iter = 2000,
         refresh = 0)
         
```


Check: 

```{r }
library(DHARMa)

pp_check(surv.m, ndraws = 100, type = "bars")
bayestestR::check_prior(surv.m)

summary(surv.m, priors = TRUE)

plot(surv.m, ask = FALSE)

stancode(surv.m)

# coef(surv.m)
fixef(surv.m)

modelbased::estimate_expectation(surv.m)

#mcmc_plot(surv.m, pars = "sampling_point")
# launch_shinystan(surv.m)

#DHARMa
surv.check <- dh_check_brms(surv.m, integer = TRUE)
plot(surv.check, form = mhdata_emerged$mh)
plot(surv.check, form = mhdata_emerged$year)
# testCategorical(surv.check, seeds.mh$mh)
#testCategorical(surv.check, seeds.mh.M$sampling_point)
testDispersion(surv.check)
# testUniformity(surv.check)

saveRDS(surv.m, here("code/models/surv.1st.summer.mh.model.rds"))
```



### Predict

```{r }

## Full posterior distributions

surv.2019 <- posterior_linpred(surv.m, 
                    newdata = data.frame(mh = sort(unique(mhdata_emerged$mh)),
                                        # emerged_seeds = 1,
                                        year = "2019"),
                    re.form = NA,
                    ndraws = 1000) %>% 
  as.data.frame() %>%
  setNames(sort(unique(mhdata_emerged$mh))) %>% 
  pivot_longer(cols = everything(), names_to = "mh", values_to = "surv.2019") %>% 
  arrange(mh)


surv.2020 <- posterior_linpred(surv.m, 
                    newdata = data.frame(mh = sort(unique(mhdata_emerged$mh)),
                                        # emerged_seeds = 1,
                                        year = "2020"),
                    re.form = NA,
                    ndraws = 1000) %>% 
  as.data.frame() %>%
  setNames(sort(unique(mhdata_emerged$mh))) %>% 
  pivot_longer(cols = everything(), names_to = "mh", values_to = "surv.2020") %>% 
  arrange(mh)

surv.post <- bind_cols(surv.2019, dplyr::select(surv.2020, -mh)) %>% 
  mutate(surv.2019 = plogis(surv.2019),
         surv.2020 = plogis(surv.2020)) %>% 
  mutate(surv.avg = (surv.2019 + surv.2020) / 2)

saveRDS(surv.post, here("data/surv.1st.summer.post.rds"))
```


```{r}
surv.post %>% 
  group_by(mh) %>% 
  summarise(median(surv.2019), median(surv.2020), median(surv.avg))

ggplot(surv.post) +
  geom_density(aes(surv.avg), fill = "lightgrey") +
  facet_wrap(~mh, ncol = 1, scales = "free_y") +
  theme(axis.text.y = element_blank()) +
  labs(title = "Average of both years")

ggplot(surv.post) +
  geom_density(aes(surv.2019), fill = "lightgrey") +
  facet_wrap(~mh, ncol = 1, scales = "free_y") +
  theme(axis.text.y = element_blank()) +
  labs(title = "2019")

ggplot(surv.post) +
  geom_density(aes(surv.2020), fill = "lightgrey") +
  facet_wrap(~mh, ncol = 1, scales = "free_y") +
  theme(axis.text.y = element_blank()) +
  labs(title = "2020")
```


```{r}
sessioninfo::session_info()
```

