---
title: "Figure bird viabilty"
date: "`r Sys.Date()`"
output: github_document
---


```{r}
library(here)
library(tidyverse)
library(ggdist)
library(patchwork)
```

Bird categorization in migration strategies
```{r}
source(here("code/bird_migration.R"))
```




Load data:
```{r}
bird.viab <- readRDS(here("data/bird.Pviab_IDs.rds")) %>%
  mutate(bird_type = ifelse(bird_sp %in% resident, "resident", 
                  ifelse(bird_sp %in% winter_migrant, "winter", "summer"))) %>% 
  mutate(bird_type = factor(bird_type, 
                          levels = c("winter", "summer", "resident"))) %>%
  mutate(bird_type = recode(bird_type,
                            "winter" = "Winter migrant",
                            "summer" = "Summer migrant",
                            "resident" = "Resident")) %>%
  mutate(bird_sp = str_replace(bird_sp, "_", " ")) %>%
  mutate(bird_sp = as.factor(bird_sp))
```

Select only barcoded species:
```{r}
bc <- read_csv(here("data/seed_rain_by_sampling_point.csv"))

only.barcoded.sp <- intersect(unique(bc$bird_sp), unique(bird.viab$bird_sp))

bird.viab.bc <- bird.viab %>%
  filter(bird_sp %in% only.barcoded.sp)

#Species removed:
setdiff(unique(bird.viab$bird_sp), unique(bc$bird_sp))
```

```{r}
bird.order.plot <- bird.viab.bc %>%
  group_by(bird_sp) %>%
  summarise(bird_type = first(bird_type),
            viab = median(viab)) %>%
  arrange(desc(bird_type), desc(viab)) %>%
  mutate(position = 1:n())

bird.order.plot
```


```{r}
bird.cols <- c("Resident" = "#d73027", 
               "Summer migrant" = "#fdae61", 
               "Winter migrant" = "#4575b4")
```


```{r}
p1 <- bird.viab.bc %>% 
  left_join(bird.order.plot[-3]) %>%
  mutate(bird_sp = recode(bird_sp, "Sylvia melanocephala" = "Curruca melanocephala",
                       "Sylvia undata" = "Curruca undata",
                       "Sylvia communis" = "Curruca communis",
                       "Sylvia hortensis" = "Curruca hortensis",
                       "Sylvia cantillans" = "Curruca iberiae")) %>%
  ggplot(aes(x = viab,
             y = fct_reorder(bird_sp, position, .desc =TRUE), 
             color = bird_type)) +
  stat_pointinterval(size = 2, 
                     .width = 0.8, 
                     interval_alpha = 0.7,
                     point_alpha = 0.7) + 
  theme_bw() + 
  theme(legend.position = "none", 
                     axis.text.x = element_blank(),
                     axis.ticks.x = element_blank(),
                     axis.text.y = element_text(face = "italic")) + 
  scale_x_continuous(limits = c(0,1)) +
  labs(x = NULL, y = NULL) +
  scale_color_manual(values = bird.cols)
```


```{r}
p2 <- bird.viab.bc %>%
  ggplot(aes(x = viab, y = bird_type, color = bird_type)) +
  scale_x_continuous(limits = c(0,1)) +
  stat_halfeye(aes(fill = bird_type), 
               slab_alpha = 0.6, point_size = 1.5) +
  theme_bw() + 
  theme(legend.position = "none") +
  labs(x = "Probability to disperse a viable seed", y = NULL) +
  scale_color_manual(values = bird.cols) +
  scale_fill_manual(values = bird.cols)
```


```{r, fig.height = 8, fig.width = 8}
p1/p2 + plot_layout(heights = c(4,1))

ggsave(here("figs/fig_viab_birds_80CI.pdf"), width = 8, height = 6)
```

